INSERT INTO Objetivo (idMapa, descricao, pontoX, pontoY, tipo)
VALUES
(1, 'Escape do hospital.', 30, 27, 'PRINCIPAL'),
(1, 'Encontre Kazuhira Miller', 29, 5, 'PRINCIPAL'),
(1, 'Extraia Kazuhira Miller', 7, 6, 'PRINCIPAL'),
(1, 'Interrogue o comandante spetsnaz', 11, 18, 'PRINCIPAL'),
(1, 'Elimine o comandante ou extraia-o para a base mãe.', 26, 21, 'PRINCIPAL'),
(1, 'Encontre o equipamento de comunicação.', 24, 3, 'PRINCIPAL'),
(1, 'Destrua o equipamento no posto de comunicação.', 15, 9, 'PRINCIPAL'),
(1, 'Extraia o Intérprete Africano', 1, 2, 'PRINCIPAL'),
(2, 'Extraia o Visconde', 1, 2, 'PRINCIPAL'),
(3, 'Neutralize o subordinado do comandante das Forças Privadas', 8, 16, 'PRINCIPAL'),
(3, 'Neutralize o comandante', 25, 19, 'PRINCIPAL'),
(3, 'Neutralize o vendedor de armas', 28, 23, 'PRINCIPAL'),
(3, 'Neutralize o oficial de Contrato das Forças da África (CFA)', 1, 2, 'PRINCIPAL'),
(3, 'Extraia o White Mamba', 1, 2, 'PRINCIPAL'),
(2, 'Extraia o Code Talker', 0, 1, 'PRINCIPAL'),
(2, 'Obtenha a fita cassete em OKB Zero', 1, 2, 'PRINCIPAL'),
(3, 'Entre em contato com Skull Face', 1, 2, 'PRINCIPAL'),
(5, 'Extraia os 2 containers com a pesquisa do code talker.', 7, 12, 'PRINCIPAL'),
(5, 'Escape do hospital', 30, 3, 'PRINCIPAL'),
(3, 'Extraia o comandante do quartel Wakh Sind', 3, 4, 'SECUNDARIO'),
(3, 'Pegue os diamantes escondidos.', 9, 0, 'SECUNDARIO'),
(3, 'Extraia o motorista do caminhão.', 8, 8, 'SECUNDARIO'),
(3, 'Obtenha as plantas medicinais perto do quartel', 1, 4, 'SECUNDARIO'),
(3, 'Obtenha os materiais processados do quartel', 2, 2, 'SECUNDARIO'),
(3, 'Extraia os 2 prisioneiros mantidos no vilarejo Wialo.', 3, 4, 'SECUNDARIO'),
(4, 'Extraia os contêineres de materiais brutos.', 3, 10, 'SECUNDARIO'),
(4, 'Obtenha os diamantes brutos escondidos.', 1, 5, 'SECUNDARIO'),
(4, 'Extraia 3 prisioneiros no campo de Kiziba', 9, 4, 'SECUNDARIO'),
(4, 'Extraia o prisioneiro mantido em Munoko ya Nioka', 7, 2, 'SECUNDARIO'),
(4, 'Extraia os containers de materiais brutos.', 10, 10, 'SECUNDARIO'),
(4, 'Obtenha os diamantes brutos.', 7, 7, 'SECUNDARIO'),
(4, 'Extraia o prisioneiro mantido no vilarejo Masa', 3, 4, 'SECUNDARIO'),
(4, 'Obtenha os diamantes brutos.', 3, 4, 'SECUNDARIO'),
(5, 'Obtenha material processado da mansão.', 10, 3, 'SECUNDARIO'),
(5, 'Obtenha os containers com materiais brutos.', 13, 2, 'SECUNDARIO'),
(5, 'Obtenha os diamantes brutos.', 3, 4, 'SECUNDARIO'),
(5, 'Obtenha material processado em OKB Zero.', 25, 1, 'SECUNDARIO'),
(5, 'Obtenha os containers com materiais brutos. ', 0, 0, 'SECUNDARIO'),
(5, 'Obtenha os diamantes brutos.', 3, 4, 'SECUNDARIO'),
(5, 'Extraia o comandante da força de segurança.Objetivos:', 3, 28, 'SECUNDARIO'),
(5, 'Elimine 6 soldados na entrada do hospital. ', 22, 4, 'SECUNDARIO');
