CREATE USER cleiton WITH PASSWORD 'cleiton123';
GRANT CONNECT ON DATABASE metalgear TO cleiton;
GRANT USAGE ON SCHEMA public TO cleiton;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO cleiton;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO cleiton;
